sudo: required
language: generic

services:
  - docker
script:
  - docker build --tag portenez/node8-base:node8.11-alpine .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push portenez/node8-base:node8.11-alpine;
    fi
